name: hs_workflow_intro_to_github_actions
on: [push]
jobs:
  show-secret-phrase:
    runs-on: ubuntu-latest
    steps:
      - name: Step with a secret
        run: |
          echo "Hello World"
          echo "This is a secret value: ${{ secrets.MY_SECRET_VALUE }}"
